"""add sender and receiver names to messages

Revision ID: 02054cdb6e86
Revises: 925f921521b1
Create Date: 2026-03-04 23:20:10.051448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02054cdb6e86'
down_revision = '925f921521b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('sender_name')
        batch_op.drop_column('receiver_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
        batch_op.add_column(sa.Column('sender_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))

    # ### end Alembic commands ###
