"""add sender and receiver names to messages

Revision ID: 925f921521b1
Revises: f442964d450a
Create Date: 2026-03-04 23:15:35.114387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925f921521b1'
down_revision = 'f442964d450a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('sender_name')

    # ### end Alembic commands ###
