"""add sale functionality to items

Revision ID: a1b2c3d4e5f6
Revises: 02054cdb6e86
Create Date: 2026-03-09 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '02054cdb6e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_for_sale', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_for_rent', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('is_for_sale', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('price_per_day',
               existing_type=sa.Numeric(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price_per_day',
               existing_type=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('is_for_sale')
        batch_op.drop_column('is_for_rent')
        batch_op.drop_column('price_for_sale')

    # ### end Alembic commands ###
