"""Add id card fields

Revision ID: e51b212ce999
Revises: e40d1a7b15e5
Create Date: 2026-02-15 19:04:14.529130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51b212ce999'
down_revision = 'e40d1a7b15e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_card_front', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_card_back', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('id_card_back')
        batch_op.drop_column('id_card_front')

    # ### end Alembic commands ###
